version: '3.8'

services:
  # chromadb:
  #   image: chromadb/chroma:latest
  #   container_name: vex-chromadb
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - CHROMA_SERVER_HOST=0.0.0.0
  #     - CHROMA_SERVER_HTTP_PORT=8000
  #     - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
  #   volumes:
  #     - chromadb_data:/chroma/chroma
  #   networks:
  #     - vex-network
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat" ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  milvus-standalone:
    image: milvusdb/milvus:v2.4.0
    container_name: vex-milvus
    command: [ "milvus", "run", "standalone" ]
    environment:
      ETCD_USE_EMBED: "true"
      ETCD_DATA_DIR: "/var/lib/milvus/etcd"
      ETCD_CONFIG_PATH: "/milvus/configs/etcd.yaml"
      MILVUS_DATA_DIR: "/var/lib/milvus/data"
      MILVUS_LOGS_DIR: "/var/lib/milvus/logs"
      MILVUS_CONF_DIR: "/milvus/configs"
    # volumes:
    #   - milvus_data:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    networks:
      - vex-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3
  # milvus-attu:
  #   image: zilliz/attu:latest
  #   container_name: vex-milvus-attu
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - MILVUS_URL=http://milvus-standalone:19530
  #   depends_on:
  #     - milvus-standalone
  #   networks:
  #     - vex-network

  # volumes:
  #   chromadb_data:
  #   milvus_data:


networks:
  vex-network:
    driver: bridge
